Update gds.yaml

diff --git a/.github/workflows/gds.yaml b/.github/workflows/gds.yaml
--- a/.github/workflows/gds.yaml
+++ b/.github/workflows/gds.yaml
@@ -22,11 +22,19 @@ jobs:
       - name: Debug copy command
         run: printf '%s\n' "${design_dir}/tt_submission/tt_um_Mr_Latch.gds"
  
+
+      - name: Check if GDS file exists
+        run: |
+         if [ ! -f "${{ github.event.inputs.design_dir }}/tt_submission/tt_um_Mr_Latch.gds" ]; then
+         echo "Error: File tt_um_Mr_Latch.gds does not exist."
+         exit 1
+         fi
+
+         
       - name: Find GDS file
         run: |
           echo "Searching in: ${{ github.event.inputs.design_dir }}"
           find "${{ github.event.inputs.design_dir }}" -name "tt_um_Mr_Latch.gds"
-       
       #- name: Find GDS file
        # run: find "${{ github.event.inputs.design_dir }}" -name "tt_um_Mr_Latch.gds"
 
